GRANT ALL PRIVILEGES ON SCHEMA public TO royal_fly;
ALTER SCHEMA public OWNER TO royal_fly;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO royal_fly;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO royal_fly;
